# Class 11/16/2022

## Sorting

Sort by the values along ether axis 
- df.sort_values('name,ascending=False)

You can sort on multiple dimensions
- df.sort_values(['Lable1','Lable2'],ascending[1,0])

In the above code, the first value will be ascending, and the second will be descending

In [12]:
import pandas as pd
import numpy as np

file_path = ('csv_files/pokemon_data.csv')
df = pd.read_csv(file_path)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [7]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total', 'Total Stats'],
      dtype='object')

In [6]:
df['Total Stats']= df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total Stats
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [26]:
df['Total Stats']= df.iloc[0:7].sum(axis=1)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Stats
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,320.0
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,408.0
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,529.0
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,629.0
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,942.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,NaN
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,NaN
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,NaN
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,NaN
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,NaN